### ISSUE TITLE
add support for [(ngModel)]

### ISSUE THREAD

**Issue by ducin** [JeanMeche/angular-compiler-output#2]
<img width="2026" alt="image" src="https://github.com/JeanMeche/angular-compiler-output/assets/375027/3e2f6321-1189-4ed3-81d3-7d88afee45dc">

a valid angular template is making the "template compiler" fail silently (no error in red gets displayed)

**Comment by JeanMeche** [comment]
Compiler output was invalid JS thus crashing prettier.
